# Generated by Django 5.1.2 on 2024-10-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='useemail',
            new_name='useremail',
        ),
    ]
