# Generated by Django 5.1.2 on 2024-10-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_useemail_signup_useremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('information', models.CharField(max_length=2000)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=150)),
                ('tag1', models.CharField(max_length=150)),
                ('tag2', models.CharField(max_length=150)),
                ('tag3', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='updateproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('information', models.CharField(max_length=2000)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=150)),
                ('tag1', models.CharField(max_length=150)),
                ('tag2', models.CharField(max_length=150)),
                ('tag3', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
