# Generated by Django 5.1.2 on 2024-10-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addproduct_updateproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='products/thumbnails/'),
        ),
        migrations.AddField(
            model_name='updateproduct',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='products/thumbnails/'),
        ),
    ]
