# Generated by Django 5.1.2 on 2024-10-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_addproduct_thumbnail_updateproduct_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='updateproduct',
            name='thumbnail',
        ),
    ]
