# Generated by Django 5.1.2 on 2024-10-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_addproduct_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
