# Generated by Django 5.1.2 on 2024-10-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_addproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='updateproduct',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
