# Generated by Django 5.1.2 on 2024-10-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_products_detail_cart_product_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='internationalshipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.IntegerField(max_length=10)),
            ],
        ),
    ]
