# Generated by Django 5.0.6 on 2024-06-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_signup_delete_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='re_pass',
            new_name='re_password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='your_email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='your_name',
        ),
    ]
