# Generated by Django 5.0.6 on 2024-06-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_employee_remove_signup_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.AddField(
            model_name='signup',
            name='re_password',
            field=models.CharField(default='password', max_length=20),
        ),
    ]
