# Generated by Django 5.0.6 on 2024-06-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_alter_signup_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signinn',
            old_name='your_pass',
            new_name='mypass',
        ),
    ]
