# Generated by Django 5.0.6 on 2024-06-21 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_addproduct_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='productimg',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
