# Generated by Django 5.0.6 on 2024-07-01 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_addproduct_productimg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cartproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('productcat', models.CharField(max_length=150)),
                ('productdes', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('productimg', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='updateproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('productcat', models.CharField(max_length=150)),
                ('productdes', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('productimg', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='cartitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.cartproducts')),
            ],
        ),
    ]
