# Generated by Django 5.0.6 on 2024-07-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_sampleforms_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
