# Generated by Django 5.0.6 on 2024-08-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_addproduct_discountprice_addproduct_productcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='productdes',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='productinfo',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='productsize',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='updateproduct',
            name='productdes',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='updateproduct',
            name='productinfo',
            field=models.CharField(max_length=2000),
        ),
    ]
